### ISSUE TITLE
Есть ли сразу готовый билд?

### ISSUE THREAD

**Issue by David491111** [OakwoodTable/CyberBiology3#2]
Здравствуйте, я не знаю язык c++, пытаясь много времени запустить программу у меня не получалось, и окончательно отчаявшись хочу спросить, в языке Java есть готовые файлы jar, есть ли такие на c++? если да то можно ли их выложить сюда, что бы не мучаться со всеми этими библиотеками и Visual Studio, если нет то можно ли скинуть архив со всеми нужными файлами пожалуйста?

**Comment by justuser-31** [comment]
Тот же вопрос - Почему так сложно скомпилировать и выложить готовые файлы?

В С++ насколько я знаю нету ничего подобного по типу .jar ,он сразу компилирует в программу.

**Comment by qwertilus** [comment]
там товарищ в пулл реквесте сделал хорошую автоматизацию. можно попробовать сделать статик билд я думаю

**Comment by ololoshka2871** [comment]
@David491111 Посмотрите в мой форк, там есть релиз последней версии.

**Comment by justuser-31** [comment]
> @David491111 Посмотрите в мой форк, там есть релиз последней версии.

Угу,спасибо.
Оно работает,было бы неплохо собрать ещё под Linux,да и Mac OS.

Работает более-менее через Steam Proton 7.0.4(форк Wine) на Линукс.

**Comment by lictw** [comment]
Тоже не понял че эт в таком прекрасном проекте экзешника нет, очень жаль..!)

**Comment by OakwoodTable** [comment]
Добавил скрипт для сборки

Пошагово как делать билд:
1 - Распакуйте код программы в отдельную папку
2 - Вручную создайте в ней папку "SDL" , поместите в неё исходный код библиотеки sdl
3 - Создайте папку "imgui" , в неё исх. код ImGui
4 - Создайте папку "implot" , в неё исх. код ImPlot
5 - Откройте файл "CMakeLists.txt" в Visual Studio (с установленным компонентом CMake tools)
6 - Выберите конфигурацию, файл для запуска и выполните билд
7 - Имейте ввиду что программа ищет папку SavedObjects рядом с бинарником, а он появится в папке /bin

**Comment by lictw** [comment]
Это очень сложно!) Это VS надо ставить, в этом всем основная проблема, а не в том что возможности нет или как делать непонятно. Если есть желание чтобы масса "поиграла в жизнь", то тут нужен прикрепленный, статичный билд, или хотя бы сборка под gcc как предлагают в параллельном ПР, это хотя бы не тянет за собой столько хлама и собирается одной командой.

На данный момент у людей не желающих ставить VS есть лишь устаревший билд от 3.09 от мистера @ololoshka2871, в любом случае спасибо!

**Comment by lictw** [comment]
А если будет поддержана gcc сборка (или что-то иное с вменяемыми инструкциями как это в контейнере каком собрать), то я могу помочь вам с автоматизацией билдов, будут по коммиту/тегу прикрепляться.

**Comment by David491111** [comment]
> Добавил скрипт для сборки
> 
> Пошагово как делать билд: 1 - Распакуйте код программы в отдельную папку 2 - Вручную создайте в ней папку "SDL" , поместите в неё исходный код библиотеки sdl 3 - Создайте папку "imgui" , в неё исх. код ImGui 4 - Создайте папку "implot" , в неё исх. код ImPlot 5 - Откройте файл "CMakeLists.txt" в Visual Studio (с установленным компонентом CMake tools) 6 - Выберите конфигурацию, файл для запуска и выполните билд 7 - Имейте ввиду что программа ищет папку SavedObjects рядом с бинарником, а он появится в папке /bin

Спасибо, сработало.

**Comment by David491111** [comment]
> Добавил скрипт для сборки
> 
> Пошагово как делать билд: 1 - Распакуйте код программы в отдельную папку 2 - Вручную создайте в ней папку "SDL" , поместите в неё исходный код библиотеки sdl 3 - Создайте папку "imgui" , в неё исх. код ImGui 4 - Создайте папку "implot" , в неё исх. код ImPlot 5 - Откройте файл "CMakeLists.txt" в Visual Studio (с установленным компонентом CMake tools) 6 - Выберите конфигурацию, файл для запуска и выполните билд 7 - Имейте ввиду что программа ищет папку SavedObjects рядом с бинарником, а он появится в папке /bin

Не работает, скорее всего я что-то не понял, но при запуске файла CMakeLists пишет что файл Systems.h не находит SDL.h который в той же папке source

**Comment by Nikiroy78** [comment]
Я скомпилировал на VStudio, однако, я из принципа не хочу пользоваться этим IDE, а на qt вылезает куча ошибок, поэтому возникает вопрос: под какой стандарт языка C++ написана данная программа

**Comment by Nikiroy78** [comment]
> > Добавил скрипт для сборки
> > Пошагово как делать билд: 1 - Распакуйте код программы в отдельную папку 2 - Вручную создайте в ней папку "SDL" , поместите в неё исходный код библиотеки sdl 3 - Создайте папку "imgui" , в неё исх. код ImGui 4 - Создайте папку "implot" , в неё исх. код ImPlot 5 - Откройте файл "CMakeLists.txt" в Visual Studio (с установленным компонентом CMake tools) 6 - Выберите конфигурацию, файл для запуска и выполните билд 7 - Имейте ввиду что программа ищет папку SavedObjects рядом с бинарником, а он появится в папке /bin
> 
> Не работает, скорее всего я что-то не понял, но при запуске файла CMakeLists пишет что файл Systems.h не находит SDL.h который в той же папке source

 Я скомпилировал всё за тебя и залил к себе: https://nikiroy78.github.io/files/Debug.rar
 
 **P.s: хер его знает, когда оно соизволит обновиться.**

**Comment by David491111** [comment]
> 

Вот теперь спасибо
