### ISSUE TITLE
Сборка проекта.

### ISSUE THREAD

**Issue by hdw0** [OakwoodTable/CyberBiology3#3]
Нужна подробная инструкция по сборке проекта. Я пробовал собирать в Ubuntu и Visual Studio. После долгих танцев с бубном
в Ubuntu wsl2 у меня следующая ошибка
`(base) windows@AndreyK-PC:~/CyberBiology3/build$ cmake --build .
Scanning dependencies of target CyberBiology
[  3%] Building CXX object CMakeFiles/CyberBiology.dir/imgui/backends/imgui_impl_sdl.cpp.o
/home/windows/CyberBiology3/imgui/backends/imgui_impl_sdl.cpp:70:10: fatal error: SDL.h: No such file or directory
   70 | #include "SDL.h"
      |          ^~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/CyberBiology.dir/build.make:141: CMakeFiles/CyberBiology.dir/imgui/backends/imgui_impl_sdl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/CyberBiology.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`

VisualStudio 2022

`Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка		CMake Error at C:\temp\CyberBiology3-main\CMakeLists.txt:123 (find_package):
  Could not find a package configuration file provided by "SDL3" with any of
  the following names:

    SDL3Config.cmake
    sdl3-config.cmake

  Add the installation prefix of "SDL3" to CMAKE_PREFIX_PATH or set
  "SDL3_DIR" to a directory containing one of the above files.  If "SDL3"
  provides a separate development package or SDK, be sure it has been
  installed.	CyberBiology	C:\temp\CyberBiology3-main\CMakeLists.txt	123	
`
Хотелось бы немного поучаствовать в проекте, но на этих проблемах уже много времени потерял.
С уважением ...

**Comment by OakwoodTable** [comment]
Здравствуйте, проверил в чем дело. Причина ошибок в том, что изменился исходный код библиотеки SDL, теперь в исходниках это версия SDL3. Насколько я понимаю на данный момент у ImGUI нет поддержки SDL3. Чтобы собрать проект скачивайте Release версию SDL2. По поводу Ubuntu помочь не могу, тут был недавно человек, который делал Linux билд, у него отдельный бранч. Хотя судя по тексту ошибки проблема та же.

**Comment by OakwoodTable** [comment]
По поводу участия в проекте, если будут вопросы по коду, пишите на почту. Правда работу над этой программой я продолжать не хочу, т.к. не вижу перспектив. Планирую сделать новую программу, с учетом всего опыта, но сейчас нет возможности ей заниматься.

**Comment by hdw0** [comment]
Да, спасибо. Я нашел ветку, которая автоматически скачивает и настраивает все необходимое и собирает и в винде и в линуксе.
Я попытался слить ветки с вашей, но с наскоку не смог. Пока вникаю в код ...
