### ISSUE TITLE
Нейросеть не получала данные о своей энергии.

### ISSUE THREAD

**Issue by hdw0** [OakwoodTable/CyberBiology3#4]
`BrainInput Bot::FillBrainInput()
{
	BrainInput input;

input.energy=(float)energy/(float)MaxPossibleEnergyForABot;

	//If destination is out of bounds
	if (!pField->IsInBounds(lookAt_x, lookAt_y))
`
Добавил изменения ...
Еще вопрос, как по человечески передать значение текущего сезона в функцию фотосинтез
`void Bot::Photosynthesis()
{
	//Above water
	if (!pField->IsInWater(y))
	{
		int toGive;

		//Give energy depending on a season
		switch (season)
		{
		case summer:
		#ifdef UseSeasons
			toGive = PhotosynthesisReward_Summer;
		#else
			toGive = pField->photosynthesisReward;
			//toGive = FindHowManyFreeCellsAround(x, y) - 3;
			//if (toGive < 0) toGive = 0;
		#endif
			break;`

Тот сезон, который тут упоминается, никогда не меняется и не связон, с тем, который переключается  ... Надеюсь понятно объяснил ...

**Comment by OakwoodTable** [comment]
1) Данные об энергии заполнялись в функции Bot::think(), там где значения структуры input переносятся непосредственно в нейроны. В следующей версии я это убрал, пока лучше оставьте так.
2) С сезонами это уже настоящая ошибка, очень давно их не использовал, с самых первых версий программы практически. Получилось что есть две разные переменные season одна в Field другая в Main. Можно пока сделать небольшой костылик и менять значение Field::season в функции ChangeSeason(). Либо исправьте на своё усмотрение. Спасибо за участие!

**Comment by hdw0** [comment]
Я в своей ветке сделал эти изменения и еще несколько настроек ... думаю проблема решена ...

**Comment by OakwoodTable** [comment]
В своей ветке вы добавили файлы проекта и код библиотек. Не уверен что разделяю такой подход. Я не смогу принимать ваши пул реквесты не смешивая проект с моим, а у вас будут трудности с внесением изменений из моей ветки. И так очень трудно смотреть коммиты, большую часть изменений составляют файлы проекта. Но воля ваша конечно. Для чего у вас используется библиотека SDL_tff?
